# =============================================================================
# Session 6 — Figures for slides
# Generates PNG files into figures/ relative to this script
# Run once before rendering slides.qmd
#
# Data required: data/happiness_income.csv
#   Generated by: make_happiness_data.R
#   Columns used: country, year, GDP_pc, happiness, population
# =============================================================================
here::i_am("sessions/session_06/session06-generate-figures.R")
library(here)
library(tidyverse)
library(patchwork)

dir.create(here("sessions/session_06/figures"), showWarnings = FALSE)

# -----------------------------------------------------------------------------
# Load data
# -----------------------------------------------------------------------------

whr <- read_csv(
  here("sessions/session_06/data/happiness_income.csv"),
  show_col_types = FALSE
) |>
  mutate(log_gdp_pc = log(GDP_pc))

# Shared style
col_point   <- "#2C5F8A"
col_line    <- "#2C5F8A"
col_smooth  <- "#D04A2F"
col_highlight <- c(
  "United States" = "#D04A2F",
  "Japan"         = "#e67e22",
  "Germany"       = "#2C5F8A",
  "United Kingdom"= "#4A9B6F",
  "China"         = "#8e44ad",
  "India"         = "#7f8c8d"
)

# =============================================================================
# Figure 1 — Cross-sectional scatter (slide 2: "Does money buy happiness?")
# One data point per country, averaged over 2017-2019 for stability
# =============================================================================

cross <- whr |>
  filter(year %in% 2017:2019) |>
  group_by(country) |>
  summarise(
    happiness   = mean(happiness,   na.rm = TRUE),
    log_gdp_pc  = mean(log_gdp_pc, na.rm = TRUE),
    population  = mean(population, na.rm = TRUE),
    .groups   = "drop"
  ) |>
  filter(!is.na(happiness), !is.na(log_gdp_pc))

p_cross_section <- cross |>
  ggplot(aes(log_gdp_pc, happiness)) +
  geom_point(aes(size = sqrt(population)), colour = col_point, alpha = 0.55) +
  scale_size_continuous(range = c(1, 8), guide = "none") +
  geom_smooth(method = "lm", colour = col_smooth, se = TRUE,
              fill = col_smooth, alpha = 0.15, linewidth = 1) +
  labs(
    x        = "Log GDP per capita (PPP)",
    y        = "Life satisfaction (0–10)",
    title    = "Richer countries are happier",
    subtitle = "Country averages, 2017–2019 · Source: World Happiness Report"
  ) +
  theme_minimal(base_size = 13) +
  theme(plot.background = element_rect(fill = "white", colour = NA))

ggsave(
  here("sessions/session_06/figures/gdp-happiness-cross-section.png"),
  p_cross_section,
  width = 8, height = 5, dpi = 180, bg = "white"
)
message("Saved: figures/gdp-happiness-cross-section.png")

# =============================================================================
# Figure 2 — Between vs. within panel (slide 5: "Two different comparisons")
# Left: cross-sectional scatter (same as Figure 1)
# Right: time series for selected countries
# =============================================================================

highlight_countries <- c("United States", "Japan", "Germany",
                         "United Kingdom", "China")

whr_highlight <- whr |>
  filter(country %in% highlight_countries, !is.na(happiness))

p_left <- cross |>
  mutate(highlighted = country %in% highlight_countries) |>
  ggplot(aes(log_gdp_pc, happiness)) +
  geom_point(
    data  = ~ filter(.x, !highlighted),
    colour = "grey70", alpha = 0.55, size = 1.8
  ) +
  geom_point(
    data  = ~ filter(.x, highlighted),
    aes(colour = country),
    size = 3, show.legend = FALSE
  ) +
  geom_smooth(method = "lm", colour = col_smooth, se = FALSE,
              linewidth = 0.8, linetype = "dashed") +
  scale_colour_manual(values = col_highlight) +
  labs(
    x        = "Log GDP per capita (PPP)",
    y        = "Life satisfaction (0–10)",
    title    = "Between countries",
    subtitle = "Richer countries are happier (cross-section)"
  ) +
  theme_minimal(base_size = 11) +
  theme(plot.background = element_rect(fill = "white", colour = NA))

p_right <- whr_highlight |>
  ggplot(aes(year, happiness, colour = country)) +
  geom_line(linewidth = 1.1) +
  geom_point(size = 1.5) +
  scale_colour_manual(values = col_highlight, name = NULL) +
  scale_x_continuous(breaks = seq(2006, 2022, by = 4)) +
  labs(
    x        = "Year",
    y        = "Life satisfaction (0–10)",
    title    = "Within countries",
    subtitle = "Income rose; happiness trends differ"
  ) +
  theme_minimal(base_size = 11) +
  theme(
    legend.position    = "bottom",
    plot.background    = element_rect(fill = "white", colour = NA),
    legend.text        = element_text(size = 9)
  )

p_between_within <- p_left + p_right +
  plot_layout(ncol = 2) &
  theme(plot.background = element_rect(fill = "white", colour = NA))

ggsave(
  here("sessions/session_06/figures/happiness-between-within.png"),
  p_between_within,
  width = 11, height = 4.5, dpi = 180, bg = "white"
)
message("Saved: figures/happiness-between-within.png")

# =============================================================================
# Done
# =============================================================================

message("\nAll session 6 figures saved to figures/")
message("Run make_happiness_data.R first to generate happiness_income.csv.")
